### ISSUE TITLE
How about submitting a DMCA Takedown Notice

### ISSUE THREAD

**Issue by ShiSheng233** [FuckOS/flyos#22]
The same as the title.

GitHub Docs: <https://docs.github.com/en/github/site-policy/guide-to-submitting-a-dmca-takedown-notice>

I think **it's time for this mess to end**.

~~BTW I've never tried to submit a DMCA Takedown Notice.~~

However, after copying so much code and not following the GPL license, there should be no problem to apply for DMCA Takedown.

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 It's hard.
but if you have a clear

**Comment by Xiaozhan-sb** [comment]
@Xiaozhan-sb 诶草，，

**Comment by Alphaly2K** [comment]
@Xiaozhan-sb 草

**Comment by Alphaly2K** [comment]
臣附议

**Comment by ShiSheng233** [comment]
Perhaps we need a complete list of infringements to apply...?

The more detail the better.

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 yes,I think you're right.

**Comment by ShiSheng233** [comment]
> @ShiSheng233 yes,I think you're right.

But I don't have that much time to do it.  

lol

Maybe someone else can do it.

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 he had done so much rubbish code that I don't have enough eyesight to find the correct or copied code.

**Comment by Alphaly2K** [comment]
@ShiSheng233 Alright. Maybe someone else can do it.

Certainly. That person WON'T be me(

**Comment by ShiSheng233** [comment]
> @ShiSheng233 he had done so much rubbish code that I don't have enough eyesight to find the correct or copied code.

That's true.

---

> @ShiSheng233 Alright. Maybe someone else can do it.
> 
> Certainly. That person WON'T be me(

hahahaha

**Comment by Alphaly2K** [comment]
@ShiSheng233 One more thing. Maybe the rubbish code which is incomprehensible will make the DMCA takedown not pass(

Who knows...

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 u'r right.

**Comment by Alphaly2K** [comment]
@ShiSheng233 By the way...

Why do we have to use English to submit the comments(

**Comment by Xiaozhan-sb** [comment]
@Xiaozhan-sb reply err，，，

**Comment by ShiSheng233** [comment]
On <https://support.github.com/contact/dmca-takedown>

![Snipaste_2021-08-18_00-01-06](https://user-images.githubusercontent.com/39020034/129760665-f110cc13-3c4c-4855-985d-6f68c0a3df3e.png)

Bad news, maybe we *(unless the copyright owner)* can't do it.

**Comment by Xiaozhan-sb** [comment]
@Alphaly2K 2 make the little five can't understand，，

**Comment by ShiSheng233** [comment]
> @ShiSheng233 By the way...
> 
> Why do we have to use English to submit the comments(

idk(((((((((

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 话说我们在这净放洋屁干什么，，，

**Comment by ShiSheng233** [comment]
Maybe we can try to get contact with the original author.

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 he has been disconnect from internet.

**Comment by Alphaly2K** [comment]
@ShiSheng233 But this is the biggest problem we cannot solve definitely, I think.

**Comment by ShiSheng233** [comment]
> @ShiSheng233 But this is the biggest problem we cannot solve definitely, I think.

True.

Because we do not hold the copyright of any of the projects.

~~So, let it go.~~

But I still hope that some authors will defend their copyrights.

Good night friends~

**Comment by ShiSheng233** [comment]
~~I apologize for this grammatical error.~~

**Comment by MSCxar-0293** [comment]
@ShiSheng233 這個

**Comment by AldarisX** [comment]
oh thats good

**Comment by ShiSheng233** [comment]
You guys can commit other plagiarism part like -> #23

**Comment by Xiaozhan-sb** [comment]
@ShiSheng233 that's uneasy......

**Comment by qwq233** [comment]
github staff will ignore if u r not the owner or contributor of the origin repo

**Comment by Alphaly2K** [comment]
@qwq233 that's obviously true
